"""Added Profile Pic

Revision ID: 039e2c5d6aec
Revises: 4152aa3194e9
Create Date: 2024-03-17 04:47:55.087898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039e2c5d6aec'
down_revision = '4152aa3194e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
