"""Added Foreing Key

Revision ID: 4152aa3194e9
Revises: 5b844b22467e
Create Date: 2024-03-16 22:41:50.272005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4152aa3194e9'
down_revision = '5b844b22467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_poster_id_users', 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_poster_id_users', type_='foreignkey')
        batch_op.drop_column('poster_id')
    
    # ### end Alembic commands ###

    # ### end Alembic commands ###
